/**
 * Auth Routes
 * 
 * Express routes for authentication endpoints
 * Generated by SmartSpec Auth Generator
 */

import { Router } from 'express';
import { AuthController } from '../controllers/auth.controller';
import { AuthMiddleware } from '../middleware/auth.middleware';

export function createAuthRoutes(
  authController: AuthController,
  authMiddleware: AuthMiddleware
): Router {
  const router = Router();

  // Public routes
  router.post('/register', authController.register.bind(authController));
  router.post('/login', authController.login.bind(authController));
  router.post('/refresh', authController.refreshTokens.bind(authController));

  router.get('/verify-email/:token', authController.verifyEmail.bind(authController));

  router.post('/forgot-password', authController.requestPasswordReset.bind(authController));
  router.post('/reset-password', authController.resetPassword.bind(authController));

  // Protected routes
  router.get('/me', authMiddleware.authenticate, authController.getCurrentUser.bind(authController));
  router.post('/change-password', authMiddleware.authenticate, authController.changePassword.bind(authController));
  router.post('/logout', authMiddleware.authenticate, authController.logout.bind(authController));

  return router;
}
