/**
 * Express Type Definitions
 * 
 * Extends Express Request type to include authenticated user
 * Generated by SmartSpec Auth Generator
 */

import { JWTPayload } from './auth.types';

declare global {
  namespace Express {
    interface Request {
      /**
       * Authenticated user payload from JWT
       * Available after authentication middleware
       */
      user?: JWTPayload;
    }
  }
}

export {};
